apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemon
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycont
        image: nginx:1.22.1
        ports:
        - containerPort: 80