apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  template:
    metadata:
      lables:
      app: nginx-my
  spec:
    containers:
      - name: nginx
        image: nginx:1.22.1
        ports:
          - containerport: 80


  selector:
    app: nginx-my