apiVersion: v1
kind: Deployment
metadata:
  name: mypod
spec:
  replicas: 4
    selector:
      matchLabels:
        app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
spec:
  containers:
  - name: deploymentcont
    image: nginx
    ports:
    - containerPort: 80