apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deployment

spec:
  replicas: 4
    selector:
      labels:
        app: my-deployment
spec:
  containers:
  - name: deploymentcont
    image: nginx
    ports:
    - containerPort: 80