apiVersion: apps/v1
kind: Pod
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  template:
    metadata:
      lables:
      app: my-nginx
  spec:
    containers:
    - name: nginx
    ports:
    - containerport: 80
  slector:
    app: my-nginx