apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-my
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-my
  template:
    metadata:
      labels:
        app: nginx-my
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

