apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycont
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Services
metadata:
  name: clusterip
spec:
  seletor:
    matchLabels:
      app: myapp
  ports:
  - name: http
    port: 30001
    target: 80